### PR TITLE
Added null safety and Flutter 2 support

### PR DESCRIPTION
**Pull request by iberatkaya**
I have added null safety support by raising the minimum Dart SDK to [2.12](https://dart.dev/null-safety/migration-guide#migrating-by-hand). I also updated the example to support Flutter 2 by recreating the Podfile with Flutter 2.

### CODE REVIEW

**Comment by chungonion** [comment]
@Vanethos It will be great to see if there are any updates on reviewing this PR. No rush but please let us know for updates 😄

**Comment by Vanethos** [comment]
Hello! sorry for the long time, it looks great! Thank you! :D

**Comment by chungonion** [comment]
Thanks man! Cheers 🥂

**Comment by aytunch** [comment]
I can not see the null safe version in pub.dev. Do you know if this will be published soon?

**Comment by chungonion** [comment]
@Vanethos Please let us know whether the update version will be available on pub.dev and once again thanks for your work!

**Comment by gsrocks-lanars** [comment]
@Vanethos did you delete 1.0.0-nullsafety.0 branch? We were using it in our project.

**Pull request merged**
